// Background script for handling iCloud API communication
console.log('1Password iCloud Hide My Email Extension loaded');

// Store authentication state
let authState = {
  isAuthenticated: false,
  sessionToken: null,
  scnt: null,
  cookies: null
};

// Listen for messages from content script
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'generateEmail') {
    handleGenerateEmail(request.label)
      .then(email => sendResponse({ success: true, email }))
      .catch(error => sendResponse({ success: false, error: error.message }));
    return true; // Keep channel open for async response
  }
  
  if (request.action === 'checkAuth') {
    sendResponse({ isAuthenticated: authState.isAuthenticated });
    return true;
  }
  
  if (request.action === 'authenticate') {
    handleAuthentication()
      .then(result => sendResponse({ success: true, result }))
      .catch(error => sendResponse({ success: false, error: error.message }));
    return true;
  }
});

// Handle iCloud authentication
async function handleAuthentication() {
  try {
    // Open iCloud login page in a new tab
    const tab = await chrome.tabs.create({
      url: 'https://www.icloud.com/',
      active: true
    });
    
    // Wait for authentication to complete
    return new Promise((resolve, reject) => {
      const timeout = setTimeout(() => {
        reject(new Error('Authentication timeout'));
      }, 300000); // 5 minute timeout
      
      // Listen for tab updates
      const listener = (tabId, changeInfo, updatedTab) => {
        if (tabId === tab.id && changeInfo.status === 'complete') {
          // Check if we're authenticated by looking for cookies
          chrome.cookies.getAll({
            domain: '.icloud.com'
          }, (cookies) => {
            const sessionCookie = cookies.find(c => c.name === 'X-APPLE-WEBAUTH-TOKEN');
            if (sessionCookie) {
              clearTimeout(timeout);
              chrome.tabs.onUpdated.removeListener(listener);
              chrome.tabs.remove(tab.id);
              
              authState.isAuthenticated = true;
              authState.sessionToken = sessionCookie.value;
              authState.cookies = cookies;
              
              resolve({ authenticated: true });
            }
          });
        }
      };
      
      chrome.tabs.onUpdated.addListener(listener);
    });
  } catch (error) {
    console.error('Authentication error:', error);
    throw error;
  }
}

// Generate a new Hide My Email address
async function handleGenerateEmail(label = '') {
  if (!authState.isAuthenticated) {
    throw new Error('Not authenticated with iCloud. Please log in first.');
  }
  
  try {
    // Get the setup-token from iCloud
    const setupResponse = await fetch('https://p95-maildomainws.icloud.com/v1/hme/setup', {
      method: 'GET',
      credentials: 'include',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      }
    });
    
    if (!setupResponse.ok) {
      throw new Error('Failed to get setup token from iCloud');
    }
    
    const setupData = await setupResponse.json();
    
    // Generate the email address
    const generateResponse = await fetch('https://p95-maildomainws.icloud.com/v1/hme/generate', {
      method: 'POST',
      credentials: 'include',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        label: label || `Generated ${new Date().toISOString().split('T')[0]}`,
        note: 'Generated by 1Password iCloud HME Extension'
      })
    });
    
    if (!generateResponse.ok) {
      const errorData = await generateResponse.json().catch(() => ({}));
      throw new Error(errorData.message || 'Failed to generate Hide My Email address');
    }
    
    const data = await generateResponse.json();
    
    if (data.result && data.result.hme) {
      return data.result.hme;
    } else if (data.hme) {
      return data.hme;
    } else {
      throw new Error('Invalid response from iCloud API');
    }
  } catch (error) {
    console.error('Error generating email:', error);
    throw error;
  }
}

// Initialize extension
chrome.runtime.onInstalled.addListener(() => {
  console.log('1Password iCloud Hide My Email Extension installed');
  
  // Set default storage values
  chrome.storage.local.set({
    autoFill: true,
    showButton: true
  });
});
